# mixed-port: 7890
port: 7890
socks-port: 7891

mode: rule

# external-controller: 127.0.0.1:9090

# tun:
#   enable: true
#   stack: system # or gvisor
#   # dns-hijack:
#   #   - 8.8.8.8:53
#   #   - tcp://8.8.8.8:53
#   auto-route: true # auto set global route
#   auto-detect-interface: true # conflict with interface-name

proxies:
  - name: "vmess"
    type: vmess
    server: 66.42.100.200
    port: 10086
    uuid: f81913a5-ba26-4042-9822-77e9d2bfabbf
    alterId: 0
    cipher: auto

rules:
  # - DOMAIN-SUFFIX,google.com,vmess
  # - DOMAIN-KEYWORD,google,vmess
  # - DOMAIN,google.com,vmess
  # - DOMAIN-SUFFIX,youtube.com,vmess
  # - DOMAIN-KEYWORD,youtube,vmess
  # - DOMAIN,youtube.com,vmess
  # - DOMAIN-SUFFIX,github.com,vmess
  # - DOMAIN-KEYWORD,github,vmess
  # - DOMAIN,github.com,vmess
  - MATCH,vmess
  